"barcode-finder":
  name: Barcode Finder
  scoring: most_matches
"bluetooth-collector":
  name: Bluetooth Collector
  duration: 15
  scoring: highest_value
"magnetometer-magnitude":
  name: Magnetometer FIXME
  duration: 30
  scoring: highest_value
"multiple-choice":
  name: Multiple Choice
  duration: 10
  scoring: most_matches
tap:
  name: Tap
  duration: 10
  scoring: highest_value
"word-collector":
  name: Word Collector
  duration: 20
  scoring: highest_value
"word-finder":
  name: Word Finder
  duration: 20
  scoring: most_matches
unplayed:
  name: Unplayed test game
